### ISSUE TITLE
is_setup returns false

### ISSUE THREAD

**Issue by hurricanehrndz** [uga-rosa/cmp-dictionary#12]
https://github.com/uga-rosa/cmp-dictionary/blob/b60df1d23ac97d6d919abcfcccedf10d1837d688/lua/cmp_dictionary/caches.lua#L167

Is it on purpose you want this to return false? I only ask because it seems to me that when update is called, more often than not setup would have already been called and config wouldn't be empty?

**Comment by uga-rosa** [comment]
This is to tell the old users to call setup because I have changed the configuration method. Originally, we used global variables.

**Comment by hurricanehrndz** [comment]
Thank you so much for the response and your efforts. Is the intended behaviour for the message to remain after the user has migrated?

**Comment by uga-rosa** [comment]
Are you calling setup with an argument? If it still happens, it is an unintentional bug and I will fix it.

**Comment by hurricanehrndz** [comment]
Yes. It also happens when setup is not called and the plug-in is only installed via packer.

**Comment by uga-rosa** [comment]
It is normal to end up here when you have not called setup. Can you show me your setup? (Just the relevant parts, please).

**Comment by hurricanehrndz** [comment]
I see you are right; it was a race condition.

**Comment by uga-rosa** [comment]
Oh, you mean the setup was called after the first caches.update? Whatever the case, I'm glad it's resolved.

**Comment by hurricanehrndz** [comment]
I believe so...
