### ISSUE TITLE
Can you give bit more clearer example of installing aspell languages?

### ISSUE THREAD

**Issue by thepenguinthatwants** [uga-rosa/cmp-dictionary#20]
You can download dic from aspell.net or installing by package manager, xbps extract to

$ ls /usr/share/dict/
american-english  british-english  words

But all I can see is just, tar.bz2 file When I uncompress it contains quite many files.
Tried to install

sudo make install and it outputs

_mkdir -p /usr/lib/aspell-0.60/
cp fi.rws fi.multi finnish.alias /usr/lib/aspell-0.60/
cd /usr/lib/aspell-0.60/ && chmod 644 fi.rws fi.multi finnish.alias
mkdir -p /usr/lib/aspell-0.60/
cp fi.dat fi_affix.dat /usr/lib/aspell-0.60/
cd /usr/lib/aspell-0.60/ && chmod 644 fi.dat fi_affix.dat_

Any clue "/usr/share/dict/ language or if its in /usr/lib/aspell-0.60/, which file it should be?

I tried
`		["*"] = { "/usr/lib/aspell-0.60/fi.rws" },`

but it didn't give me any completions

**Comment by uga-rosa** [comment]
I added it to the readme. See also #19.
