### ISSUE TITLE
[feature] support bidding filename and dict

### ISSUE THREAD

**Issue by fcying** [uga-rosa/cmp-dictionary#21]
Currently, dict bidding to the file type.
Can you add an option to specify the file name to use the corresponding dict? e.g.
```
filename = {
    ["xmake.lua" ] = { "xmake.dict", "lua.dict" }
}
```
Some special files, not use file type.

**Comment by uga-rosa** [comment]
done

**Comment by fcying** [comment]
It work fine, thanks~~
