### ISSUE TITLE
No suggestion for for existing  words with mistake.

### ISSUE THREAD

**Issue by JoseConseco** [uga-rosa/cmp-dictionary#25]
Hi, I'm not sure if spellcorrection is in scope of this plugin but I noticed dict suggest words only for new  typed in words, but it wont suggest anything of existing words with spell mistake:

https://user-images.githubusercontent.com/13521338/153725534-f5c9a3b5-1dab-4f75-8d2d-ccebe9872c3f.mp4

In video above TabNine suggested correction, but I got not entries from cmp-dict.

Any chances for cmp-dict to suggest correction for  spelling mistakes?

**Comment by uga-rosa** [comment]
Thank you very much. This is a bug. I will fix it. The correct behavior is to look before the cursor, so the candidate appears for 'sent'.
![image](https://user-images.githubusercontent.com/82267684/153797075-c5a59797-a5c2-41df-b0c3-8f1be77ba458.png)

**Comment by uga-rosa** [comment]
9ae00514826bd26b84d86d67ed999cb4155c33e4

**Comment by JoseConseco** [comment]
thanks. Btw. is there way to force cmp-dict  to take whole word under cursor into account?  The way it works now, it only 'checks' for letter that are before cursor. It would be cool if it could check whole workd  (and replace it too, rather than what is before cursor).   
I will close this.

**Comment by uga-rosa** [comment]
If you bring the cursor to the end of a word with `ea`, it will consider the whole word, but isn't that what you're talking about?

**Comment by JoseConseco** [comment]
yest that works ok.  I just wish, cmp-dict could work if cursor in in the middle if word (kind of like cmp-tabnine where it takes into account whole word) , But that is not big deal .  Thanks for the fix
