### ISSUE TITLE
Feat: Add dynamic preview using Wordnet

### ISSUE THREAD

**Issue by BerkeleyTrue** [uga-rosa/cmp-dictionary#26]
I just recently built out an fzf and Rofi commands that will pull from the same dictionary I'm using with cmp-dictionary that will give me a preview of the word overview or return the overview in the case of Rofi. Here is the guide I used. https://ddrscott.github.io/blog/2017/fzf-dictionary/

It would be great if we could get that same sort of preview with cmp-dictionary. Maybe just the option to configure the preview in the setup step.

**Comment by uga-rosa** [comment]
branch: wordnet created. Is this what you mean?

**Comment by BerkeleyTrue** [comment]
Perfect!
![image](https://user-images.githubusercontent.com/6775919/155565499-245ddd8c-9213-4b91-8bd4-c599aaaf2f5a.png)
