### ISSUE TITLE
iskeyword

### ISSUE THREAD

**Issue by martineausimon** [uga-rosa/cmp-dictionary#28]
Hi, is there a way to use iskeyword fonction ?

I have a dictionary with words like `\word` and `another`, and it seems impossible to make the iskeyword function working.
I have already try that in my ftplugin : 

    vim.cmd[[set iskeyword+=\]]

and 

    vim.opt.iskeyword:append([[\]])

Is there a solution ?
Thanks !

Thanks !

**Comment by uga-rosa** [comment]
`iskeyword` is now referenced in the completion.

**Comment by martineausimon** [comment]
Thank you ! It works perfect !
