### ISSUE TITLE
Set dictionary based on vim `spelllang`?

### ISSUE THREAD

**Issue by farbodsz** [uga-rosa/cmp-dictionary#29]
Sometimes I write prose in English, or in other languages within vim, and adjust vim's `spelllang` option to get spelling corrections.

Is it possible to configure `cmp-dictionary` so that the dictionary (and list of words for completion) changes, depending on what `spelllang` option is set?

**Comment by uga-rosa** [comment]
I would like to know what exactly you would like to do. It is not possible to dynamically change the completion candidates as it is now, but probably not that big a change should be necessary. I don't know about the performance impact, though.

**Comment by farbodsz** [comment]
Yes exactly - I'm imagining something like this:

1. User defines dictionary sources for various languages (English, French, German, etc) in their configuration
2. User changes `spelllang` during their editing session
3. Active dictionary source is updated dynamically

If it would have a large performance impact, I'm happy just to specify those sources together, so that completion for all languages shows up, regardless of what I've set as `spelllang`.

**Comment by uga-rosa** [comment]
I see, you don't want to put the result of spellsuggest() as a candidate, you want to register a dictionary for each spelllang like the current implementation of filetype and filepath?

**Comment by uga-rosa** [comment]
Added.
Please register language and dictionary in `dic.spelllang` during setup. The plugin cannot detect changes in `spelllang`, so be sure to run `CmpDictionaryUpdate` when `spelllang` is changed.
