### ISSUE TITLE
Russian spelllang dictionary

### ISSUE THREAD

**Issue by 0xRZ** [uga-rosa/cmp-dictionary#31]
Hello, thank you for the plugin. Can you please hint me on how to set up suggestions from russian dictionary? I have the following `init.vim`:
```vimscript
let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir . '/autoload/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'uga-rosa/cmp-dictionary'
call plug#end()

if len(filter(values(g:plugs), '!isdirectory(v:val.dir)'))
	echom 'Some modules are missing, running :PlugInstall'
	PlugInstall --sync
endif

lua <<EOF

local cmp = require('cmp')

require("cmp_dictionary").setup({
	dic = {
		spelllang = {
			en = "/path/to/en.dict",
			ru = "/path/to/ru.dict",
		},
	},
})

cmp.setup{
  mapping = {
		["<C-j>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_next_item()
			end
		end, { "i", "s" }),
		["<C-k>"] = cmp.mapping(function(fallback)
			if cmp.visible() then
				cmp.select_prev_item()
			end
		end, { "i", "s" }),
		['<C-l>'] = cmp.mapping({
			i = cmp.mapping.confirm({ select = false }),
		}),
	},

	sources = {
		{
			name = "dictionary",
			keyword_length = 2,
		},
	}
}

EOF

set keymap=russian-jcuken
set spelllang=ru
```
But I do not get any completions as I type in russian:
![image](https://user-images.githubusercontent.com/46892933/186610406-65ed5e21-345c-4503-8576-25c1ae8b3a38.png)
Executing `CmpDictionaryUpdate` after entering buffer also does not help.

While english seems to work fine:
![image](https://user-images.githubusercontent.com/46892933/186610762-7594af96-6e42-4024-a855-ec2863a81fd9.png)

I use `aspell-en` and `aspell-ru` packages on archlinux and the following command to get dictionaries:
```bash
aspell -d en dump master | aspell -l en expand > en.dict
aspell -d ru dump master | aspell -l ru expand > ru.dict 
```

**Comment by uga-rosa** [comment]
It may be a problem with the cmp itself (it does not handle multibyte characters well). Please wait while we investigate.

**Comment by uga-rosa** [comment]
Fixed in 843e2f5e7372f797ae8c0cdf1462bbe36fc0b0ab
Please update the latest version and test it.

**Comment by 0xRZ** [comment]
Yeah, I see it works now, thank you.
Tho, completion is really slow, can I speed up it somehow? I see that russian dictionary in aspell after expansion is really huge, is it possible to truncate it?
![Peek 2022-08-27 13-35](https://user-images.githubusercontent.com/46892933/187026592-c0332da9-b62e-45d2-9e63-8045aa9322cf.gif)

**Comment by uga-rosa** [comment]
The candidate acquisition itself is done by bisection search, so I don't think it will be that slow. I think that a large number of candidates are passed to the main body of cmp, and the subsequent sorting and display process may be taking time. I will try to create a mechanism to limit the number of candidates returned to the main body.

**Comment by uga-rosa** [comment]
Can you try #32?

**Comment by 0xRZ** [comment]
Well, it doesn't lag, but results of completion seems odd

**Comment by uga-rosa** [comment]
That's right. If we return all the candidates, it would be too heavy, so to avoid that, we reduce the number of candidates to be returned.
Increase the number of `max_items` in setup, or increase the number of `exact`, or set it to -1 (the candidates returned by this plugin to the main body are those looked for by forward exact match for `exact` only, and fuzzy match is the job of the main body).

**Comment by uga-rosa** [comment]
Please try and let me know how much these should be set to just the right numbers, as I would like to determine the appropriate default settings.

**Comment by uga-rosa** [comment]
PR for max_items has been merged. The default value is set to -1 (unlimited).
Please make good use of options `max_items` and `exact`.

**Comment by 0xRZ** [comment]
Thank you
```
max_items = 2000,
exact = -1,
```
works decent for Russian language
