### ISSUE TITLE
Accept function for dic and/or file type or provide other means to set buffer-specific dictionaries

### ISSUE THREAD

**Issue by naquad** [uga-rosa/cmp-dictionary#38]
I have the following configuration:

```lua
require('cmp_dictionary').setup {
  dic = {
    ['*'] = '/usr/share/dict/words',
    ledger = '<secret location>/accounting/accounts.txt'
  }
}
```

While it mostly works there are a number of issues with this configuration.

1. This is a static configuration that can't be customized in the runtime. Think `set dictionary+=asd.txt` so one can set dictionaries specific to the particular buffer.
2. The configuration is "global", i.e. you can't customize the configuration per buffer.
3. All the configuration made using `'dictionary` and `'thesaurus` is ignored :(

I've been using a lot of dictionaries and have quite a few configurations for file types, frameworks, and so forth. It would be great to see the support of `'dictionary` and/or `'thesaurus` in cmp-dictionary. If that's too much work then at least accept a function instead of the string for specifying the dictionary would be very appreciated.

**Comment by uga-rosa** [comment]
To allow more user flexibility, I plan to eliminate the dic in setup and refer to the value of the dictionary option. I have been busy lately and the work has been slow, but I will do it soon, so please be patient for a while.

**Comment by uga-rosa** [comment]
I have merged v2. Can you do what you wanted to do?

**Comment by naquad** [comment]
From what I see in the help and the Wiki, there are no changes related to this task. No function can be set for the dictionaries, and the `'dictionary` setting is not handled.

Am I missing something?

**Comment by uga-rosa** [comment]
Please see them.

https://github.com/uga-rosa/cmp-dictionary/blob/main/doc/cmp-dictionary.txt#L23-L28
https://github.com/uga-rosa/cmp-dictionary/blob/main/doc/cmp-dictionary.txt#L186-L193

**Comment by naquad** [comment]
Ah, now I see, thank you for the clarification. My experiment has shown that after `set dictionary=path/to/some/dict.txt` a call to `:CmpDictionaryUpdate` is still required, even when using the switcher despite the docs. Is that correct?

[![asciicast](https://asciinema.org/a/yK97H2Uo9Vjy20NtK4A9oVzIE.svg)](https://asciinema.org/a/yK97H2Uo9Vjy20NtK4A9oVzIE)

**Comment by naquad** [comment]
Ah, thank you for the clarification, now I got it. Although, after some testing, it seems that I still have to call `:CmpDictionaryUpdate` even when the switcher is used, despite what the docs say. Is that correct?

Demo: [![asciicast](https://asciinema.org/a/6SBoNOg0H5eviIVwpC3CrkP5B.svg)](https://asciinema.org/a/6SBoNOg0H5eviIVwpC3CrkP5B)

P. S. Previous message demo link is broken, please ignore it.

**Comment by uga-rosa** [comment]
It's not a bug (only `FileType`, `BufEnter`, and `OptionSet spelllang` have been registered), but it sure would be nice to have automatic updates in the `OptionSet dictionary`.

**Comment by uga-rosa** [comment]
Added automatic update function in `OptionSet dictionary`.

**Comment by naquad** [comment]
Works great! Thank you :)
