### ISSUE TITLE
Multi-word entries & a dictionary separated by newlines.

### ISSUE THREAD

**Issue by RobinTruax** [uga-rosa/cmp-dictionary#47]
Hi, lovely plugin. I am configuring Neovim into an editor for prose mathematics. I am creating a dictionary of math terminology, and I'd like to use multi-word phrases in said dictionary. For example, the phrase 'finite-dimensional vector space' occurs with high frequency. I have a dictionary of such entries, possibly multi-word, separated by newlines. Right now, the plugin separates all of these into their own entries ('finite-dimensional', 'vector', 'space'). Is there a way to use such a dictionary with your plugin? I poked around for a bit and didn't see a quick way to enable such an option, though I'm not familiar with the codebase.

**Comment by uga-rosa** [comment]
The plugin is designed to be compatible with vim's built-in dictionary completion function (:h i_CTRL-X_CTRL-K), and the format of the dictionary is also similar. Also, this is a common dictionary format in linux (/usr/share/dict/words).
I would like to protect compatibility in this plugin, but nvim-cmp itself can fulfill your wishes. Why don't you add candidates directly yourself with [this issue](https://github.com/uga-rosa/cmp-dictionary/issues/44) or use [cmp-dynamic](https://github.com/uga-rosa/cmp-dynamic)? In cmp-dynamic, there is no obligation to use a function, so it can also be used as a way to pass arbitrary [CompletionItem](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#completionItem) directly.

**Comment by RobinTruax** [comment]
This makes sense, thank you for the recommendations!

**Comment by RobinTruax** [comment]
This makes sense, thank you for the recommendations.
