### ISSUE TITLE
Possibility to show which dictionary does a word belong to ?

### ISSUE THREAD

**Issue by vorban** [uga-rosa/cmp-dictionary#5]
For example, with the `cmp-path` plugin, the type (file/folder) of each choice is displayed:

![image](https://user-images.githubusercontent.com/16322680/142216331-3ea3ad07-8def-489a-88c5-c23776b578d6.png)

Is there any way to get the source dictionary in the same way ?

For example, I have two dictionary files: path/to/dic/EN and path/to/dic/FR. I would like, instead of the `Text` placeholder, have the corresponding file (EN/FR in my case) :

![image](https://user-images.githubusercontent.com/16322680/142217240-97afb2a2-515d-4a14-8f55-122bfeff8071.png)

I don't have any dev experience in lua nor vim so I really don't know how feasible that would be based on your implementation.

Regardless, thank you for your time and efforts with this nice plugin 😃

**Comment by uga-rosa** [comment]
That's a feature embedded in the main unit. As you can see here, what I can specify from the source are 25 enums (which are actually numbers) that correspond to LSP items, and the corresponding text is displayed. "Text" itself is not specified by this plugin (maybe).

https://github.com/hrsh7th/nvim-cmp/blob/286b9f78d1013d4f4d3a70efcc803d00912dfe35/lua/cmp/types/lsp.lua#L108

**Comment by uga-rosa** [comment]
Oh, I asked hrsh7th about it, and it looks like it can be done, so I'll try it when I wake up (it's midnight in my country now, so I'm going to bed).

**Comment by uga-rosa** [comment]
I have `dictionary=/usr/share/dict/words`, so it shows up like this. What do you think?

![image](https://user-images.githubusercontent.com/82267684/142367313-a03d71f6-c844-4eaa-aa26-6294f07531ed.png)

**Comment by uga-rosa** [comment]
There's no reply, so I'll close it.

**Comment by vorban** [comment]
My apologies, I was incapacitated for the past few months.

This is indeed what I was looking for, thank you very much !
