### ISSUE TITLE
Unclear step to generate a dictionaries

### ISSUE THREAD

**Issue by AndresMpa** [uga-rosa/cmp-dictionary#51]
### Please write a foolproof "How to" 

This line of code is not clear enough to me:

```
aspell -d <lang> dump master | aspell -l <lang> expand > my.dict
```

I' m not common with `aspell` What is "lang"? Also, How can I list the avalible one I have in my OS?

Each time I use the command I'm getting an error that says:

```
Error: The file "/usr/lib/aspell-0.60/en_US" can not be opened for reading.   # What I understand as a permission error
```

But, in a docker container I made I get the expected long list of words from aspell

**Comment by uga-rosa** [comment]
Look at the official aspell documentation. This project is not aspell. GIYF
