### ISSUE TITLE
Error message in trie.lua

### ISSUE THREAD

**Issue by kekscode** [uga-rosa/cmp-dictionary#58]
Any idea what i do wrong here?

Error on startup:

```
Error executing luv callback:
...vim/lazy/cmp-dictionary/lua/cmp_dictionary/dict/trie.lua:45: bad argument #1 to 'decode' (string expected, got nil)
stack traceback:
	[C]: in function 'decode'
	...vim/lazy/cmp-dictionary/lua/cmp_dictionary/dict/trie.lua:45: in function <...vim/lazy/cmp-dictionary/lua/cmp_dictionary/dict/trie.lua:44>
Error in luv thread:
...vim/lazy/cmp-dictionary/lua/cmp_dictionary/dict/trie.lua:42: too deep to serialize
```

Config (lazy):

```lua
  {
    "uga-rosa/cmp-dictionary", -- dictionary manager
    enabled = true,
    build =
    'brew install aspell && brew install wordnet && aspell -d en dump master | aspell -l en expand >$HOME/en.dict && aspell -d de dump master | aspell -l de expand >$HOME/de.dict',
    config = function()
      require("cmp_dictionary").setup({
        paths = {
          "/usr/share/dict/words", vim.fn.expand('$HOME/de.dict'), vim.fn.expand('$HOME/en.dict'),
        },
        exact_length = 2,
        first_case_insensitive = true,
        document = {
          enable = true,
          command = { "wn", "${label}", "-over" },
        },
      })
    end
  },
```

neovim:

```
 vim --version
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1703358377

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/opt/homebrew/Cellar/neovim/0.9.5/share/nvim"

Run :checkhealth for more info
```

**Comment by uga-rosa** [comment]
Hmm. This is the first error I've seen, but the cause is predictable. You are using a dictionary that contains rather long words, aren't you?
I can solve the problem itself (using vim.json to serialize), but it slows me down somewhat.
Can you tell me what dictionary you are using?

**Comment by uga-rosa** [comment]
Does 51c48f9 fix it?

**Comment by uga-rosa** [comment]
Hmmm, there is supposed to be a single word with more than 500 bytes. Perhaps it is not compatible with the new format of the dictionary.

**Comment by uga-rosa** [comment]
I have checked the dictionary and understand. It's because of the change in dictionary specifications (`:h cmp-dictionary-option-paths`).
I only used newlines as word separators (to be able to use external commands like look, grep, etc.). If you replace all the white space in the dictionary with newlines, it should work.

**Comment by uga-rosa** [comment]
I corrected `Find dictionaries` chapter of the documentation.

**Comment by uga-rosa** [comment]
I'm glad it's fixed.
This error is caused by vim.json (cjson) and string.buffer library (LuaJIT), so I can't do anything about it.

**Comment by Myzel394** [comment]
I'm facing the same issue though creating a new dict using `aspell -d de dump master | aspell -l de expand | sed 's/\s\+/\n/g' > de.dict` doesn't work for me :/
