### ISSUE TITLE
Depreciated warnings?

### ISSUE THREAD

**Issue by dky** [uga-rosa/cmp-dictionary#65]
Hello, thanks for the plugin. I'm running into the following errors:

[cmp-dictionary] 'exact' is deprecated. Use 'exact_length' instead.
[cmp-dictionary] 'capacity' is deprecated.

after upgrading to nvim 0.9.5. Do you know if they will be fixed in: https://github.com/uga-rosa/cmp-dictionary/issues/56?

**Comment by uga-rosa** [comment]
Please read the help documantation.

**Comment by dky** [comment]
Ok Thanks! I think I fixed it. I changed exact => exact_length and removed the capacity key.

**Comment by uga-rosa** [comment]
Yes. Your fixes are right.
