### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Joarell** [uga-rosa/cmp-dictionary#66]
Hi!
Could you please give me some assistance to understand what's going wrong on my config?

![image](https://github.com/uga-rosa/cmp-dictionary/assets/42722369/2e3a0837-3c08-47bc-a6fd-d47559d187bb)
![image](https://github.com/uga-rosa/cmp-dictionary/assets/42722369/bc04e0e8-fab6-465e-a1f5-113ed9fd3b9c)

**Comment by uga-rosa** [comment]
Please include the """minimum""" (A small one, consisting of really minimal elements needed to reproduce this bug) configuration file that can be reproduced independently and the steps required to reproduce it. I am not a psychic.

**Comment by Joarell** [comment]
Sorry.
I added the image with my config settings, as you can see on my first message.
What I know is when I turn the dictionary off, the bug is gone.

In the last version of the plugin, it's never happened. So, I don't know enough about your modifications on the current version of the plugin to figure it out what to do or where is the cause of it.
Again, I'm sorry to not provide you a great info about. Despite that, could you please guide me to find something that is value to help you fix this?

**Comment by Joarell** [comment]
![dict-nvim](https://github.com/uga-rosa/cmp-dictionary/assets/42722369/3c0c16cf-2104-4160-a572-533f521bc1e6)

**Comment by stamina** [comment]
Hi, had the same error as you. It's probably the updated cmp-dictionary settings (document -> command -> wn). My Arch linux didn't have the "wn" (wordnet) command. I Installed the AUR wordnet-common and wordnet-cli packages.

That fixed it, gl!

**Comment by Joarell** [comment]
Thank you, @stamina!
I use the Xerolinux, it's an Arch base linux as well.
I installed `wordnet-common` and `wordnet-cli` and the `Error` was gone!

Thanks a lot!
Have a nice day you all! 👍🏾

**Comment by Joarell** [comment]
Thank you, @stamina!
I use the Xerolinux, it's an Arch base linux as well.
I installed `wordnet-common` and `wordnet-cli` and the `Error` was gone!

Thanks a lot!
Have a nice day you all! 👍🏾
