### ISSUE TITLE
Question: wasn't this repo archived/not maintained?

### ISSUE THREAD

**Issue by farzadmf** [uga-rosa/cmp-dictionary#69]
Hi there,

Am I dreaming or at some point this year, you announced that this repo will be unmaintained (and I remember it even being actually archived).

Please tell me my brain isn't playing tricks on me! 🤯

**Comment by uga-rosa** [comment]
Circumstances have changed and I have decided to use nvim-cmp again. Therefore, I have decided to resume maintenance of this repository.

**Comment by farzadmf** [comment]
Oh OK, cool, so I was _not_ dreaming!

Question, if you don't mind: were you using some alternative to `nvim-cmp` when you decided to archive this repo?

Thank you for letting me know, closing this as it was just a question

**Comment by uga-rosa** [comment]
ddc.vim
https://github.com/Shougo/ddc.vim

I decided to focus on stability since it is used for business purposes.

**Comment by farzadmf** [comment]
Oh interesting; so you're using `coc.nvim` _and_ `nvim-cmp`? I thought `coc` would have its own "everything"
