### ISSUE TITLE
Getting autocomplete for ONLY the first 2 characters

### ISSUE THREAD

**Issue by iamhrigved** [uga-rosa/cmp-dictionary#71]
### When I type "ad" it gives autocomplete on it BUT,
![image](https://github.com/uga-rosa/cmp-dictionary/assets/170752613/06a590cc-d0a9-4717-8b78-c750d5e39c4f)
### When I the type "v", I get no result
![image](https://github.com/uga-rosa/cmp-dictionary/assets/170752613/236590d3-6dfa-4431-8413-86466d207c92)
I should get some results like "advertisement" and "advocate" but... nothing
### Even when I type the full thing, I get nothing
![image](https://github.com/uga-rosa/cmp-dictionary/assets/170752613/2752d390-0ef5-44ed-80d7-aa4e2d021a1d)

## My minimal config
```lua
require("cmp").setup({
    sources = {
        { name = "dictionary", keyword_length = 2, }
    }
})

require("cmp_dictionary").setup({
    paths = { "/usr/share/dict/words" },
    exact_length = 2,
    max_number_items = 5,
    first_case_insensitive = true,
    document = {
	enable = true,
	command = { "wn", "${label}", "-over" },
    },
})
```

**Comment by uga-rosa** [comment]
You shouldn't set max_number_items.

**Comment by iamhrigved** [comment]
When I remove the `max_number_items` It becomes very laggy.

**Comment by uga-rosa** [comment]
Do you use a considerably large dictionary?
Please provide the number of words included in the dictionary you are using. Also, please provide a way to prepare that dictionary if possible.

By using keyword_length and exact_length, only candidates whose first two characters match exactly are returned to nvim-cmp itself.
If there are still several tens of thousands of candidates after this narrow down, filtering and sorting in cmp will take a lot of time and become laggy.

**Comment by iamhrigved** [comment]
I did `sudo apt install wordnet` which has 155,327 words (just googled).
What is the preferable way to setup the dictionary? I didn't find any docs regarding this, so I did what I thought was right.

**Comment by uga-rosa** [comment]
To find out how many words a file contains, you can use the wc command.

```bash
wc /usr/share/dict/words
```

My dictionary contains 104334 English words and works comfortably with the following settings.

```lua
require("cmp").setup({
  -- other settings...
  sources = {
    -- other sources...
    { name = "dictionary", keyword_length = 2 },
  },
})

require("cmp_dictionary").setup({
  paths = { "/usr/share/dict/words" },
  exact_length = 2,
  first_case_insensitive = true,
})
```

**Comment by iamhrigved** [comment]
```zsh
$ wc /usr/share/dict/words
663473  663473 6922426 /usr/share/dict/words
```
I have 663,473 words

Oh wait... It's suddenly working fine! I don't know what happened. Thanks.
