### ISSUE TITLE
Couple of changes/improvements

### ISSUE THREAD

**Issue by farzadmf** [uga-rosa/cmp-dictionary#72]
Hey @uga-rosa 

When you archived this repo, I created a fork, and I _think_ I fixed a couple of issues in it, with the main one being: if I press `ctrl+space` to open auto-complete menu and I do it when there's no word under my cursor, I think the plugin will try to parse the whole dictionary, basically freezing everything (at least that was my impression, and I think I've fixed it).

These are [my changes](https://github.com/uga-rosa/cmp-dictionary/compare/main...farzadmf:cmp-dictionary:main).

If you're OK with the changes, I can create a PR (minus the README changes of course)

**Comment by uga-rosa** [comment]
That's not the right fix. What we should be looking at here should be keyword_length, not exact_length.

**Comment by uga-rosa** [comment]
Thanks for pointing this out. I have corrected it in this commit.
42866957964aa698d53f222395dbd1e334e77fdd

**Comment by farzadmf** [comment]
Great, thank you @uga-rosa
