### ISSUE TITLE
Enabling depends on treesitter (comment) support? 

### ISSUE THREAD

**Issue by Jaehaks** [uga-rosa/cmp-dictionary#76]
Thank you for your efforts, 

Could cmp-dictionary enable in only comment region?

**Comment by uga-rosa** [comment]
https://github.com/hrsh7th/nvim-cmp/issues/806

**Comment by Jaehaks** [comment]
I'll try, Thanks:)

**Comment by uga-rosa** [comment]
Could you close this issue?
