### ISSUE TITLE
Is anyone experiencing low memory issues?

### ISSUE THREAD

**Issue by Jaehaks** [uga-rosa/cmp-dictionary#77]
If the size of word file is 4.0MB, is it too heavy? 

When I use this word list, memory usage of nvim increases about 30 times, (40MB -> 1.2GB).

**Comment by uga-rosa** [comment]
That's strange. There might be a memory leak.

However, I am using a 2.5MB dictionary, and I did not observe a sudden increase in memory usage due to this plugin. Are there any other conditions?

**Comment by Jaehaks** [comment]
It is weid, It could be a windows error.
