### ISSUE TITLE
Is it possible to configure this plugin for dictd?

### ISSUE THREAD

**Issue by khorn06** [uga-rosa/cmp-dictionary#78]
Is it possible to supply a list of words directly instead of reading them from a file?

For example, with [dictd](https://wiki.archlinux.org/title/Dictd), I can run the following command to generate a list of words for auto-completion:

`$ dict -s re -m ^prefix\\w*$`

**Comment by uga-rosa** [comment]
This plugin provides a method to use an external command instead of a file as a dictionary.
Please read help doc (`:h cmp-dictionary-option-external`).
